apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: "###ZARF_CONST_NAME###"
  namespace: bigbang
spec:
  interval: 10m
  url: "###ZARF_CONST_REPO###"
  ref:
    tag: "###ZARF_CONST_TAG###"
