apiVersion: v1
stringData:
  values.yaml: |
    {{- .Values.baseValues | toYaml | nindent 4 }}
  overlay.yaml: |
    {{- .Values.overlayValues | nindent 4 }}
kind: Secret
metadata:
  name: bigbang-{{- .Values.application.name -}}-values
  namespace: bigbang
type: generic
